blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/jesusoliveira/ghost/discussions
    about: Faca perguntas, compartilhe ideias e converse com a comunidade do Ghost.
